 
services:  
  catalogdb:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    
  catalog:
    image: catalog
    build:
      context: .
      dockerfile: Services/Catalog/Catalog/Dockerfile   

volumes:
  postgres_catalog:  

  
